// Code generated by hanamaru generator; DO NOT EDIT.
package main

import(
	"hanamaru/commands/debug"
	"hanamaru/commands/fun"
	"hanamaru/commands/fun"
	"hanamaru/commands/fun"
	"hanamaru/commands/image"
	"hanamaru/commands/image"
	"hanamaru/commands/image"
	"hanamaru/commands/image"
	"hanamaru/commands/image"
	"hanamaru/commands/image"
	"hanamaru/commands/image"
	"hanamaru/commands/info"
	"hanamaru/commands/info"
	"hanamaru/commands/info"
	"hanamaru/commands/info"
	"hanamaru/commands/info"
	"hanamaru/commands/jp"
	"hanamaru/commands/jp"
	"hanamaru/commands/music"
	"hanamaru/commands/music"
	"hanamaru/commands/music"
	
)

func init() {
	hanamaru.AddCommand(debug.ListArgs)
	hanamaru.AddCommand(fun.Dance)
	hanamaru.AddCommand(fun.Suntsu)
	hanamaru.AddCommand(fun.Talk)
	hanamaru.AddCommand(image.Bishop)
	hanamaru.AddCommand(image.Braile)
	hanamaru.AddCommand(image.CAS)
	hanamaru.AddCommand(image.Jpg)
	hanamaru.AddCommand(image.Latex)
	hanamaru.AddCommand(image.Rumble)
	hanamaru.AddCommand(image.Stretch)
	hanamaru.AddCommand(info.About)
	hanamaru.AddCommand(info.Avatar)
	hanamaru.AddCommand(info.Invite)
	hanamaru.AddCommand(info.ServerInfo)
	hanamaru.AddCommand(info.UserInfo)
	hanamaru.AddCommand(jp.Pitch)
	hanamaru.AddCommand(jp.Romaji)
	hanamaru.AddCommand(music.Join)
	hanamaru.AddCommand(music.Leave)
	hanamaru.AddCommand(music.Play)
	
}
