name: Run Tests and Build

on: [push]
jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13.1"
      - run: go version
      - run: go generate ./...
      - run: go test ./...
      - run: go build -o artifacts/hanamaru.exe
        if: runner.os=='Windows'
      - run: go build -o artifacts/hanamaru
        if: runner.os=='Linux'
