name: Run Tests and Build

on: [push]
jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        tags: ["jp", ""]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13.1"
      - run: go version
      - run: go generate ./...
      - run: go test ./...
      - run: GOOS=windows GOARCH=amd64 go build -tags ${{matrix.tags}} -o artifacts/hanamaru-${{matrix.tags}}.exe
      - run: GOOS=linux GOARCH=amd64 go build -tags ${{matrix.tags}} -o artifacts/hanamaru-${{matrix.tags}}
