name: ci

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      
      - name: Login
        uses: docker/login-action@v1
        with:
          username: treelar
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: "."
          push: true
          platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8"
          tags: treelar/hanamaru:latest