name: Run Tests and Build

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13.1"
      - run: go version
      - name: Setup Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go
      - run: mage buildCI
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hanamaru-all
          path: artifacts/*
      - uses: docker/build-push-action@v1.1.0
        with:
          username: treelar
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: treelar/hanamaru
          tags: latest
