name: Build and Upload to Docker
on:
  push:
    branches:
      - master
jobs:
  docker:
    name: Build and Upload to Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: treelar
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: treelar/hanamaru
          tags: latest


